### ISSUE TITLE
Add an optional index argument to network update methods

### ISSUE THREAD

**Issue by hbsmith** [ELIFE-ASU/Neet#11]
This adds ability for asynchronous updating

**Comment by dglmoore** [comment]
I will work on getting the basic infrastructure for asynchronous updating setup toward the end of the week. As discussed during the GRN meetings, I think the best approach is to have an optional `index` argument for the network `update` methods. If `index is None`, then the entire state is updated. Otherwise, only the provided index is updated.

From this basic setup we can build generic functions that compute the "trajectory tree" (made that up) rooted at any given state, and from that all of the interesting algorithms can follow.

Does anyone have any thoughts on this?
