### ISSUE TITLE
Data Visualization

### ISSUE THREAD

**Issue by hbsmith** [ELIFE-ASU/Neet#14]
suggestions of what these should be? figures from overleaf doc? This should be broken out into multiple issues.

**Comment by dglmoore** [comment]
## Initial Thoughts
I think there are three aspects to this issue: **network visualization**, **landscape visualization** and **data visualization**. In my opinion, the first two are features that we definitely want to build into Neet since they are fairly generic. All networks of a given type (e.g. `WTNetwork`) can be visualized similarly, and all (finite) attractor landscapes can be visualized similarly. Data visualization is a bit tricker. I would prefer to err on the side of *not* providing data visualization, but that I have a feeling I will be overridden (which is totally reasonable). If that's the case, we should try to stick to the most common visualizations such as TE scaling.

## API Suggestions

### Network Visualization
I'm thinking that each network type (e.g. `WTNetwork`, `LogicNetwork`, `ECA`, etc...) should have a method called `show`. All of the arguments to that function should be *optional* keyword arguments that have sensible defaults. The rationale behind this is that it is nice to have a roughly uniform API over all of the types. We can then write functions that take any network type and call its methods without much specialization -- you can have a function call `show` without caring about the network type.

### Landscape Visualization
This might just be a thin wrapper around `NetworkX` used for visualizing state transitions graphs? **What do we think of this?**

### Data Visualization
Functions such as `transfer_entropy` might take optional `plot=[True|False]` arguments that create standard plot for that particular analysis? (This will have to wait until we actually have analyses... 😞 )

**Comment by hbsmith** [comment]
I agree with this assessment. 

I also agree with very minimal "data" visualization functionality. I'm imagining at most a handful of common visualizations for things like local/global AI or TE.

**Comment by hbsmith** [comment]
This issue will add visualization for 1. network itself (or CA itself), 2. Landscape. Everything else can be plotted using your favorite library, using that libraries functions.

**Comment by dglmoore** [comment]
@hbsmith How is this going? Do you need any help?

**Comment by hbsmith** [comment]
@dglmoore I haven't look at this in a few weeks. Depending on our priorities, I can give this a shot today (I am planning to start identifying async vs. sync nets on cell collective data first). I was getting hung-up on producing a nice default visualization for a range of transition landscapes earlier.

As far as the networks themselves, @bcdaniels appeared to have a good working solution as of 2 meetings ago. It would be nice to have one library or application which can reliably plot networks at the scale of the network and the landscape, but this might not be possible because of how finicky network visualizations are.

Perhaps we should break this into two issues. 1. Visualization of networks and 2. Visualization of Landscapes. @bcdaniels can submit a pull request to fulfill 1, and I can take a shot at 2 later. Thoughts?

**Comment by hbsmith** [comment]
I think we're going to include examples of how to visualize different things within the example jupyter notebooks, such as the landscape, the network, and some information examples without adding specialized neet code for visualization in version 0.1.0.
