### ISSUE TITLE
Standardized way to access network connectivity

### ISSUE THREAD

**Issue by bcdaniels** [ELIFE-ASU/Neet#75]
A basic property of a network is "which nodes are connected".  In the language of neet, this corresponds to the set of state variables that influence each state variable in the update function.

At the moment, we do not require neet networks to specify a connectivity structure, but having one can be very useful — e.g. for visualization, making randomized versions of existing networks, and making sensitivity calculations much more efficient.

I propose that we either require the network connectivity when defining a neet network or have a way to calculate and store it in a standardized format for later use.

**Comment by hbsmith** [comment]
I think having the ability to convert to a networkx type graph will provide
this type of functionality. But we could also make this independent of that
if desired.

**Comment by dglmoore** [comment]
@hbsmith I think we should *minimize* how much we use `networkx` graphs. They are obscenely inefficient to construct.

**Comment by hbsmith** [comment]
I was thinking about our "null edge" problem in logic networks (where node 1 points to node 2, but node 1's state does not actually influence node 2's state), and I think we also have this problem with ECAs, when converting ECAs to network edge connections. Some rules will only depend on the leftmost two squares for instance, because maybe the right square being 0 or 1 doesn't change the next state. Is there an easy way to identify these rules for neighbor connectivity purposes?
